#!/usr/bin/env python3
"""Generate narrative result documents and small SVG charts for the Kafka lab."""

from __future__ import annotations

import html
import json
import os
from pathlib import Path
from typing import Any


OUTPUT_DIR = Path(os.environ.get("OUTPUT_DIR", "/data"))


def load_results() -> dict[str, Any]:
    return json.loads((OUTPUT_DIR / "results.json").read_text(encoding="utf-8"))


def scenario(data: dict[str, Any], experiment_name: str, scenario_name: str) -> dict[str, Any]:
    for experiment in data["experiments"]:
        if experiment["name"] == experiment_name:
            for item in experiment["scenarios"]:
                if item["name"] == scenario_name:
                    return item["metrics"]
    raise KeyError(f"{experiment_name}/{scenario_name}")


def group_scenarios(data: dict[str, Any]) -> list[dict[str, Any]]:
    for experiment in data["experiments"]:
        if experiment["name"] == "consumer_group_parallelism":
            return [item["metrics"] for item in experiment["scenarios"]]
    raise KeyError("consumer_group_parallelism")


def write_svg_bar_chart(filename: str, title: str, labels: list[str], values: list[float], ylabel: str) -> None:
    width = 820
    height = 420
    margin_left = 90
    margin_right = 30
    margin_top = 62
    margin_bottom = 96
    plot_width = width - margin_left - margin_right
    plot_height = height - margin_top - margin_bottom
    max_value = max(values) if values else 1
    max_value = max(max_value, 1)
    bar_gap = 28
    bar_width = (plot_width - bar_gap * (len(values) - 1)) / max(len(values), 1)
    colors = ["#2f6f73", "#c45131", "#7567a8", "#4f7cac", "#8a6f2a"]

    parts = [
        f'<svg xmlns="http://www.w3.org/2000/svg" width="{width}" height="{height}" viewBox="0 0 {width} {height}">',
        '<rect width="100%" height="100%" fill="#fbfaf7"/>',
        f'<text x="{width / 2}" y="34" text-anchor="middle" font-family="Arial, sans-serif" font-size="22" font-weight="700" fill="#1d2528">{html.escape(title)}</text>',
        f'<text x="24" y="{margin_top + plot_height / 2}" transform="rotate(-90 24 {margin_top + plot_height / 2})" text-anchor="middle" font-family="Arial, sans-serif" font-size="13" fill="#455">{html.escape(ylabel)}</text>',
        f'<line x1="{margin_left}" y1="{margin_top + plot_height}" x2="{width - margin_right}" y2="{margin_top + plot_height}" stroke="#344" stroke-width="1"/>',
        f'<line x1="{margin_left}" y1="{margin_top}" x2="{margin_left}" y2="{margin_top + plot_height}" stroke="#344" stroke-width="1"/>',
    ]
    for index, (label, value) in enumerate(zip(labels, values)):
        x = margin_left + index * (bar_width + bar_gap)
        bar_height = (value / max_value) * plot_height
        y = margin_top + plot_height - bar_height
        color = colors[index % len(colors)]
        parts.append(f'<rect x="{x:.1f}" y="{y:.1f}" width="{bar_width:.1f}" height="{bar_height:.1f}" fill="{color}"/>')
        parts.append(f'<text x="{x + bar_width / 2:.1f}" y="{y - 8:.1f}" text-anchor="middle" font-family="Arial, sans-serif" font-size="13" fill="#1d2528">{value:.2f}</text>')
        parts.append(f'<text x="{x + bar_width / 2:.1f}" y="{height - 58}" text-anchor="middle" font-family="Arial, sans-serif" font-size="13" fill="#1d2528">{html.escape(label)}</text>')
    parts.append("</svg>")
    (OUTPUT_DIR / filename).write_text("\n".join(parts), encoding="utf-8")
    print(f"Generated: {OUTPUT_DIR / filename}")


def markdown_table(rows: list[tuple[str, Any]]) -> str:
    lines = ["| Metric | Value |", "| --- | ---: |"]
    for key, value in rows:
        lines.append(f"| {key} | {value} |")
    return "\n".join(lines)


def report(data: dict[str, Any]) -> str:
    dataset = data["dataset"]
    rr = scenario(data, "partitioning_and_ordering", "round_robin")
    repo = scenario(data, "partitioning_and_ordering", "repo_keyed")
    actor = scenario(data, "partitioning_and_ordering", "actor_keyed")
    lag = scenario(data, "consumer_lag_drain", "repo_keyed_backlog")
    groups = group_scenarios(data)
    group_rows = "\n".join(
        f"| {item['requested_consumers']} | {item['active_consumers']} | {item['partition_count']} | {item['records']} |"
        for item in groups
    )
    top_types = ", ".join(f"{item['name']}={item['count']}" for item in dataset["top_event_types"][:5])
    top_repos = ", ".join(f"{item['name']}={item['count']}" for item in dataset["top_repos"][:5])
    top_actors = ", ".join(f"{item['name']}={item['count']}" for item in dataset["top_actors"][:5])

    return f"""# Kafka Demo Lab Result

This report was generated by a Docker Compose run against a real Kafka broker. The input data is the fixed GH Archive hour `2024-01-01-0.json.gz`; the experiment downloads that public archive, verifies MD5 `{dataset['md5']}`, parses every event, produces the events to Kafka, consumes them back, and then writes these measurements. The numbers below are not hand-written expected output.

## Dataset

{markdown_table([
    ("Source URL", dataset["url"]),
    ("Compressed bytes", dataset["compressed_bytes"]),
    ("Event records", dataset["event_count"]),
    ("Distinct event types", dataset["distinct_event_types"]),
    ("Distinct repositories", dataset["distinct_repos"]),
    ("Distinct actors", dataset["distinct_actors"]),
    ("Time range start", dataset["first_created_at"]),
    ("Time range end", dataset["last_created_at"]),
])}

Top event types: {top_types}

Top repositories by event count: {top_repos}

Top actors by event count: {top_actors}

The dataset is representative for a Kafka lab because it is an append-only event stream with natural event ids, event types, actor ids, repository ids, skewed keys, and one-hour ordering semantics.

## Partitioning And Ordering

![Partition skew](partition-skew.svg)

| Scenario | Records consumed | Partitions used | Min partition count | Max partition count | Max/min ratio | Key partition violations | Per-key order violations |
| --- | ---: | ---: | ---: | ---: | ---: | ---: | ---: |
| Round-robin/no key | {rr['records']} | {rr['partitions_used']} | {rr['min_partition_count']} | {rr['max_partition_count']} | {rr['max_min_ratio']:.4f} | {rr['key_partition_violations']} | {rr['per_key_order_violations']} |
| Key = repo.id | {repo['records']} | {repo['partitions_used']} | {repo['min_partition_count']} | {repo['max_partition_count']} | {repo['max_min_ratio']:.4f} | {repo['key_partition_violations']} | {repo['per_key_order_violations']} |
| Key = actor.id | {actor['records']} | {actor['partitions_used']} | {actor['min_partition_count']} | {actor['max_partition_count']} | {actor['max_min_ratio']:.4f} | {actor['key_partition_violations']} | {actor['per_key_order_violations']} |

Round-robin production spreads records across all 12 partitions with nearly equal counts. Keyed production also uses all partitions, but real-world key skew changes partition load. The verifier checks that each `repo.id` or `actor.id` stays on one partition and that the per-key sequence consumed from Kafka remains ordered.

## Consumer Group Parallelism

![Consumer group parallelism](consumer-groups.svg)

| Requested consumers | Active consumers | Topic partitions | Records consumed |
| ---: | ---: | ---: | ---: |
{group_rows}

Kafka consumer group parallelism is bounded by partition count. When the requested consumer count exceeds 12 partitions, extra consumers do not receive records in this run.

## Lag Drain

![Lag drain](lag-drain.svg)

| Measurement | Records |
| --- | ---: |
| Initial backlog after production | {lag['initial_lag_records']} |
| Consumed at checkpoint | {lag['checkpoint_consumed']} |
| Backlog at checkpoint | {lag['checkpoint_lag_records']} |
| Final backlog after drain | {lag['final_lag_records']} |

The lag scenario uses the produced `repo.id` keyed topic as the backlog. The consumer starts behind the producer, observes a non-zero backlog, and drains it to zero after reading all produced records.

## Conclusion

- Kafka partitions are the unit of parallelism. More consumers than partitions do not increase active parallelism for one topic.
- A key maps all records for the same entity to one partition, which preserves per-key order but can create partition skew when the real traffic distribution is skewed.
- Consumer lag is accumulated produced-but-unconsumed records. It falls to zero only when consumers catch up with the topic offsets.
"""


def main() -> int:
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)
    data = load_results()
    rr = scenario(data, "partitioning_and_ordering", "round_robin")
    repo = scenario(data, "partitioning_and_ordering", "repo_keyed")
    actor = scenario(data, "partitioning_and_ordering", "actor_keyed")
    lag = scenario(data, "consumer_lag_drain", "repo_keyed_backlog")
    groups = group_scenarios(data)

    write_svg_bar_chart(
        "partition-skew.svg",
        "Partition max/min ratio",
        ["round-robin", "repo key", "actor key"],
        [rr["max_min_ratio"], repo["max_min_ratio"], actor["max_min_ratio"]],
        "max/min partition count",
    )
    write_svg_bar_chart(
        "consumer-groups.svg",
        "Active consumers vs requested consumers",
        [str(item["requested_consumers"]) for item in groups],
        [float(item["active_consumers"]) for item in groups],
        "active consumers",
    )
    write_svg_bar_chart(
        "lag-drain.svg",
        "Backlog drains after consumption",
        ["initial", "checkpoint", "final"],
        [float(lag["initial_lag_records"]), float(lag["checkpoint_lag_records"]), float(lag["final_lag_records"])],
        "records",
    )

    text = report(data)
    (OUTPUT_DIR / "result.md").write_text(text, encoding="utf-8")
    (OUTPUT_DIR / "report.md").write_text(text, encoding="utf-8")
    print(f"Generated: {OUTPUT_DIR / 'result.md'}")
    print(f"Generated: {OUTPUT_DIR / 'report.md'}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
